---
  - name: Install Spacewalk-setup-postgresql
    yum: name=spacewalk-setup-postgresql state=present
    environment:
      http_proxy: "{{ proxy_env.http_proxy }}"
      https_proxy: "{{ proxy_env.https_proxy }}"
      no_proxy: "{{ proxy_env.no_proxy }}"
  
  - name: Postgres - Initialisation instance
    become_user: postgres
    command: /usr/bin/pg_ctl initdb  -D /var/lib/pgsql/data/
    
  - name: Postgres - Starting instance
    become_user: postgres
    command: /usr/bin/pg_ctl start -D /var/lib/pgsql/data/  -w -t 300

  - name: Posgres - Create DATABASE spaceschema
    become_user: postgres
    command: psql -c 'CREATE DATABASE spaceschema'

  - name: Postgres - Create user spaceuser
    become_user: postgres
    command: psql -c "CREATE USER spaceuser WITH PASSWORD 'spacepw'" 

  - name: Postgres - Alter user spaceuser
    become_user: postgres
    command: psql -c 'ALTER ROLE spaceuser SUPERUSER'

  - name: Postgres - pltclu
    become_user: postgres
    command: createlang pltclu spaceschema
    