---
  - name: Install Spacewalk-setup-postgresql
    yum: name=spacewalk-setup-postgresql state=present
    environment:
      http_proxy: {{ proxy_env.http_proxy }}
      https_proxy: {{ proxy_env.https_proxy }}
      no_proxy: {{ proxy_env.no_proxy }}