---
- hosts: localhost
  sudo: yes
  vars_files:
    - secrets/{{site}}-secrets.yml
  roles:
    - repo-epel
    - spacewalk
    - role: iptables
      firewall_allowed_tcp_ports:
      - 22
      - 80
      - 443
      - 5222
      - 5269
      - 68
      - 69


- hosts: localhost
  sudo: yes
  vars_files:
    - secrets/{{site}}-secrets.yml
  roles:
    - role: spacewalk-customisations
      spacewalk_admin_password: "{{ admin_password }}"
    - role: spacewalk-client