---

# Delegate further configuration to subtasks
# placed in this same directory.

- include: install.yml
- include: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'Debian'
- include: CentOS.yml
  when: ansible_os_family == 'CentOS'

- name: Debian - Ensure supervisord is running
  sudo: yes
  service:
    name: "{{supervisord_service_name}}"
    state: running
    enabled: yes
  tags:
    - init
    - supervisor
    - supervisord
  when: ansible_os_family == 'Debian'
  
- name: CentOS-RedHat - run supervisord
  shell: if [ ! -S /var/run/supervisor.sock ]; \
    then sudo /var/www/imd/venv/bin/supervisord \
    -c /var/www/imd/deploy/supervisord.conf; fi
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
  
- name: CentOS-RedHat - Ensure supervisord is running
  sudo: yes
  systemd: state=started name="{{supervisord_service_name}}"
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"