---

- name: restart supervisord
  sudo: yes
  service: name=supervisor state=restarted
  tags:
    - supervisord-restart

- name: reread supervisord
  sudo: yes
  command: supervisorctl reread
  tags:
    - supervisord-reread

- name: update supervisord
  sudo: yes
  command: supervisorctl update
  tags:
    - supervisord-update
