---
#############
# Please checkout your secret/{{ site }}-secrets.yml vault file
#############
spacewalk_admin_email: "{{ vault_spacewalk_admin_email }}"
spacewalk_ssl_org: "{{ vault_spacewalk_ssl_org }}"
spacewalk_ssl_org_unit: "{{ vault_spacewalk_ssl_org_unit }}"
spacewalk_ssl_set_city: "{{ vault_spacewalk_ssl_set_city }}"
spacewalk_ssl_set_state: "{{ vault_spacewalk_ssl_set_state }}"
spacewalk_ssl_set_country: "{{ vault_spacewalk_ssl_set_country }}"
spacewalk_ssl_password:  "{{ vault_spacewalk_ssl_password }}"
spacewalk_ssl_set_email: "{{ vault_spacewalk_ssl_set_email }}"
spacewalk_ssl_config_sslvhost: Y
spacewalk_db_backend: postgresql
spacewalk_db_name: spaceschema
spacewalk_db_user: spaceuser
spacewalk_db_password: spacepw
spacewalk_db_host: localhost
spacewalk_db_port: 5432
spacewalk_enable_tftp: Y


